const RELEASE = 'RC9 V0.21';
const LEGACY_KEY = 'qanteak.rc9.v0.20.foundations';
const FALLBACK_KEY = 'qanteak.rc9.v0.21.platform';
const PROPERTY_TYPES = ['text','number','currency','percentage','select','multi_select','status','checkbox','date','person','file','url','email','phone','relation','rollup','formula','created_time','created_by','edited_time','edited_by','unique_id','button'];
const CONNECTOR_CATALOG = [
  ['gmail','Gmail','Email search/actions','OAuth credentials'],['outlook','Outlook','Email + calendar','OAuth credentials'],['google-calendar','Google Calendar','Calendar events','OAuth credentials'],['google-drive','Google Drive','Files and knowledge','Existing Qanteak Drive foundation'],['onedrive','OneDrive / SharePoint','Files and enterprise knowledge','OAuth credentials'],['github','GitHub','Code, issues and pull requests','OAuth/app credentials'],['slack','Slack','Messages and channels','OAuth credentials'],['teams','Microsoft Teams','Chats and channels','OAuth credentials'],['jira','Jira','Issues and projects','API credentials'],['linear','Linear','Issues and cycles','OAuth credentials'],['figma','Figma','Design context','OAuth credentials'],['crm','CRM adapter','Salesforce / HubSpot class systems','Provider credentials'],['support','Support adapter','Zendesk class systems','Provider credentials']
];

const $ = (s,r=document) => r.querySelector(s);
const $$ = (s,r=document) => [...r.querySelectorAll(s)];
const esc = v => String(v ?? '').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const uid = (prefix='q') => `${prefix}_${crypto.randomUUID ? crypto.randomUUID() : Math.random().toString(36).slice(2)}_${Date.now().toString(36)}`;
const now = () => new Date().toISOString();
const fmtDate = v => { if(!v) return '—'; try { return new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric',year:'numeric'}).format(new Date(String(v).slice(0,10)+'T12:00:00')); } catch { return String(v); } };
const fmtTime = v => { try { return new Date(v).toLocaleString(); } catch { return String(v||''); } };
const clamp = (n,min,max) => Math.min(max,Math.max(min,Number(n)||0));
const slug = v => String(v||'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,48) || uid('field');

function blankState(){
  return {
    version:21, release:RELEASE, schemas:[], objects:[], views:[], forms:[], dashboards:[], automations:[], approvals:[], contexts:[], skills:[], agents:[], comments:[], citations:[], webhooks:[], connectors:[], instructions:{workspace:'',user:''}, governance:{requireApprovalForWrites:true,externalActionsEnabled:false,computerUseEnabled:false,allowedTools:['search','read','create_object','update_object','run_automation'],allowedModels:['local-deterministic'],retentionDays:365}, audit:[], platform:{apiEnabled:false,port:32145,mcpEnabled:false}, migratedFromV020:false, createdAt:now(), updatedAt:now()
  };
}
let state = blankState();
let activeTab = 'overview';
let currentSchemaId = null;
let apiStatus = {enabled:false,configured:false,port:32145,token:'',baseUrl:'http://127.0.0.1:32145',mcpPath:'/mcp'};
let saveTimer = null;

async function platformLoad(){
  try {
    if(window.qanteakDesktop?.platformLoad) return await window.qanteakDesktop.platformLoad();
  } catch(e){ console.warn('V0.21 platform load failed',e); }
  try { return JSON.parse(localStorage.getItem(FALLBACK_KEY)||'null') || blankState(); } catch { return blankState(); }
}
async function platformSave(next=state){
  state.updatedAt = now();
  try {
    if(window.qanteakDesktop?.platformSave) { state = await window.qanteakDesktop.platformSave(state); return state; }
  } catch(e){ console.warn('V0.21 platform save failed',e); }
  localStorage.setItem(FALLBACK_KEY,JSON.stringify(state));
  return state;
}
function scheduleSave(){ clearTimeout(saveTimer); saveTimer=setTimeout(()=>platformSave(),120); }
function audit(action,detail='',actor='local-user'){
  state.audit = Array.isArray(state.audit)?state.audit:[];
  state.audit.unshift({id:uid('audit'),action,detail:String(detail||''),actor,at:now()});
  state.audit=state.audit.slice(0,2000); scheduleSave();
}
function toast(message,kind='good'){
  const host=$('#toastHost'); if(!host)return;
  const el=document.createElement('div'); el.className=`toast ${kind}`; el.textContent=message; host.append(el); setTimeout(()=>el.remove(),3600);
}

function field(type,label,extra={}){ return {id:uid('fld'),key:slug(label),label,type,...extra}; }
function defaultFields(){ return [field('text','Name',{required:true}),field('status','Status',{options:['New','In progress','Blocked','Done']}),field('person','Owner'),field('date','Date')]; }
function normalizeState(raw){
  const b=blankState(), s={...b,...(raw||{})};
  for(const key of ['schemas','objects','views','forms','dashboards','automations','approvals','contexts','skills','agents','comments','citations','webhooks','connectors','audit']) if(!Array.isArray(s[key])) s[key]=[];
  s.instructions={...b.instructions,...(s.instructions||{})}; s.governance={...b.governance,...(s.governance||{})}; s.platform={...b.platform,...(s.platform||{})};
  return s;
}
function migrateV020(){
  if(state.migratedFromV020) return;
  let old=null; try{old=JSON.parse(localStorage.getItem(LEGACY_KEY)||'null')}catch{}
  if(old){
    for(const db of old.databases||[]){
      const schema={id:uid('schema'),name:db.name||'Imported database',description:db.description||'Migrated from V0.20',fields:defaultFields(),createdAt:now(),updatedAt:now()};
      state.schemas.push(schema);
      const [nameF,statusF,ownerF,dateF]=schema.fields;
      for(const row of db.rows||[]) state.objects.push({id:uid('obj'),type:'record',schemaId:schema.id,title:row.name||'Untitled',values:{[nameF.id]:row.name||'Untitled',[statusF.id]:row.status||row.stage||'New',[ownerF.id]:row.owner||'Workspace',[dateF.id]:row.date||''},relations:[],owner:row.owner||'Workspace',source:'v0.20-migration',createdAt:now(),updatedAt:now()});
      state.views.push({id:uid('view'),schemaId:schema.id,name:'Table',type:'table',filters:[],sorts:[],groupBy:'',visibleFields:schema.fields.map(f=>f.id),createdAt:now()});
    }
    for(const g of old.goals||[]) state.objects.push({id:uid('obj'),type:'goal',title:g.title||'Goal',owner:g.owner||'Workspace',values:{progress:Number(g.progress||0),due:g.due||''},relations:[],source:'v0.20-migration',createdAt:now(),updatedAt:now()});
    audit('V0.20 workspace migrated',`${(old.databases||[]).length} databases and ${(old.goals||[]).length} goals`,'system');
  }
  if(!state.schemas.length){
    const schema={id:uid('schema'),name:'Projects database',description:'Universal structured work records.',fields:defaultFields(),createdAt:now(),updatedAt:now()};
    state.schemas.push(schema);
    state.views.push({id:uid('view'),schemaId:schema.id,name:'Table',type:'table',filters:[],sorts:[],groupBy:'',visibleFields:schema.fields.map(f=>f.id),createdAt:now()});
  }
  state.migratedFromV020=true; scheduleSave();
}

function schema(id){ return state.schemas.find(s=>s.id===id); }
function object(id){ return state.objects.find(o=>o.id===id); }
function records(schemaId){ return state.objects.filter(o=>o.type==='record'&&o.schemaId===schemaId); }
function fieldDef(schemaId,fieldId){ return schema(schemaId)?.fields?.find(f=>f.id===fieldId); }
function nameField(s){ return s?.fields?.find(f=>f.required&&f.type==='text') || s?.fields?.find(f=>f.type==='text') || s?.fields?.[0]; }
function objectTitle(o){ if(!o)return'Untitled'; if(o.title)return o.title; const s=schema(o.schemaId),nf=nameField(s); return String(o.values?.[nf?.id]||o.name||'Untitled'); }
function relationTargets(value){ return Array.isArray(value)?value:(value?[value]:[]); }
function num(v){ const n=Number(v); return Number.isFinite(n)?n:0; }

function formulaTokens(input){
  const src=String(input||'').trim().replace(/^=/,''); const out=[]; let i=0;
  while(i<src.length){ const c=src[i]; if(/\s/.test(c)){i++;continue;} if(/[0-9.]/.test(c)){let j=i+1;while(j<src.length&&/[0-9.]/.test(src[j]))j++;out.push({t:'num',v:Number(src.slice(i,j))});i=j;continue;} if(c==='"'||c==="'"){const q=c;let j=i+1,s='';while(j<src.length&&src[j]!==q){if(src[j]==='\\'&&j+1<src.length){j++;s+=src[j++];}else s+=src[j++];}out.push({t:'str',v:s});i=Math.min(src.length,j+1);continue;} if(/[A-Za-z_]/.test(c)){let j=i+1;while(j<src.length&&/[A-Za-z0-9_]/.test(src[j]))j++;out.push({t:'id',v:src.slice(i,j)});i=j;continue;} const two=src.slice(i,i+2); if(['>=','<=','==','!=','&&','||'].includes(two)){out.push({t:'op',v:two});i+=2;continue;} if('+-*/%><(),!'.includes(c)){out.push({t:'op',v:c});i++;continue;} throw new Error(`Unsupported token: ${c}`); }
  return out;
}
function evalFormula(expr,record,s){
  if(!expr)return''; const toks=formulaTokens(expr); let p=0;
  const peek=()=>toks[p],take=()=>toks[p++];
  const propValue=name=>{const f=s.fields.find(x=>x.label.toLowerCase()===String(name).toLowerCase()||x.id===name||x.key===name);return f?computedValue(record,s,f):''};
  const funcs={PROP:(a)=>propValue(a),IF:(c,a,b)=>c?a:b,ROUND:(a,b=0)=>Number(num(a).toFixed(num(b))),CONCAT:(...a)=>a.map(x=>x??'').join(''),COALESCE:(...a)=>a.find(x=>x!==''&&x!==null&&x!==undefined)??'',ABS:a=>Math.abs(num(a)),MIN:(...a)=>Math.min(...a.map(num)),MAX:(...a)=>Math.max(...a.map(num)),SUM:(...a)=>a.reduce((n,x)=>n+num(x),0)};
  const prec={'||':1,'&&':2,'==':3,'!=':3,'>':4,'<':4,'>=':4,'<=':4,'+':5,'-':5,'*':6,'/':6,'%':6};
  function primary(){ const t=take(); if(!t)return''; if(t.t==='num'||t.t==='str')return t.v; if(t.v==='('){const v=parse(0);if(take()?.v!==')')throw new Error('Missing )');return v;} if(t.v==='!' )return !primary(); if(t.v==='-')return -num(primary()); if(t.t==='id'){const id=t.v.toUpperCase(); if(peek()?.v==='('){take();const args=[];if(peek()?.v!==')'){while(true){args.push(parse(0));if(peek()?.v===','){take();continue;}break;}}if(take()?.v!==')')throw new Error('Missing )'); if(!funcs[id])throw new Error(`Unknown function ${id}`);return funcs[id](...args);} if(id==='TRUE')return true;if(id==='FALSE')return false;if(id==='NULL')return null;return propValue(t.v);} return''; }
  function parse(min){let left=primary();while(peek()&&prec[peek().v]>=min){const op=take().v,right=parse(prec[op]+1); if(op==='+')left=(typeof left==='string'||typeof right==='string')?String(left??'')+String(right??''):num(left)+num(right);else if(op==='-')left=num(left)-num(right);else if(op==='*')left=num(left)*num(right);else if(op==='/')left=num(right)===0?0:num(left)/num(right);else if(op==='%')left=num(right)===0?0:num(left)%num(right);else if(op==='>')left=left>right;else if(op==='<')left=left<right;else if(op==='>=')left=left>=right;else if(op==='<=')left=left<=right;else if(op==='==')left=left==right;else if(op==='!=')left=left!=right;else if(op==='&&')left=Boolean(left&&right);else if(op==='||')left=Boolean(left||right);}return left;}
  return parse(0);
}
function rollupValue(record,s,f){
  const relField=s.fields.find(x=>x.id===f.relationFieldId); if(!relField)return''; const ids=relationTargets(record.values?.[relField.id]); const targets=ids.map(object).filter(Boolean); const vals=targets.map(o=>{const targetSchema=schema(o.schemaId);const tf=targetSchema?.fields?.find(x=>x.id===f.targetFieldId);return tf?computedValue(o,targetSchema,tf):'';}); const op=f.operation||'count';
  if(op==='count')return vals.length;if(op==='sum')return vals.reduce((a,b)=>a+num(b),0);if(op==='average')return vals.length?vals.reduce((a,b)=>a+num(b),0)/vals.length:0;if(op==='min')return vals.length?Math.min(...vals.map(num)):0;if(op==='max')return vals.length?Math.max(...vals.map(num)):0;if(op==='earliest')return vals.filter(Boolean).sort()[0]||'';if(op==='latest')return vals.filter(Boolean).sort().at(-1)||'';if(op==='percent_checked')return vals.length?Math.round(vals.filter(Boolean).length/vals.length*100):0;return vals.join(', ');
}
function computedValue(record,s,f){
  if(!record||!s||!f)return''; if(f.type==='formula'){try{return evalFormula(f.formula||'',record,s)}catch{return'Formula error';}} if(f.type==='rollup')return rollupValue(record,s,f); if(f.type==='created_time')return record.createdAt||''; if(f.type==='edited_time')return record.updatedAt||''; if(f.type==='created_by')return record.createdBy||record.owner||'Local user'; if(f.type==='edited_by')return record.editedBy||record.owner||'Local user'; if(f.type==='unique_id')return record.id; return record.values?.[f.id] ?? '';
}
function displayValue(record,s,f){ const v=computedValue(record,s,f); if(f.type==='checkbox')return v?'✓':'—'; if(f.type==='date'||f.type==='created_time'||f.type==='edited_time')return v?fmtDate(v):'—'; if(f.type==='currency')return Number.isFinite(Number(v))?new Intl.NumberFormat(undefined,{style:'currency',currency:f.currency||'USD'}).format(Number(v)):'—'; if(f.type==='percentage')return `${num(v)}%`; if(f.type==='relation')return relationTargets(v).map(id=>objectTitle(object(id))).join(', ')||'—'; if(Array.isArray(v))return v.join(', '); return String(v||'—'); }

function filteredRecords(s,view){
  let rows=[...records(s.id)]; for(const f of view?.filters||[]){rows=rows.filter(r=>{const fd=s.fields.find(x=>x.id===f.fieldId),v=String(computedValue(r,s,fd)??'').toLowerCase(),x=String(f.value??'').toLowerCase(); if(f.op==='contains')return v.includes(x);if(f.op==='equals')return v===x;if(f.op==='not_equals')return v!==x;if(f.op==='gt')return num(v)>num(x);if(f.op==='lt')return num(v)<num(x);if(f.op==='empty')return !v;return true;});}
  for(const sort of [...(view?.sorts||[])].reverse()){const fd=s.fields.find(x=>x.id===sort.fieldId);rows.sort((a,b)=>String(computedValue(a,s,fd)??'').localeCompare(String(computedValue(b,s,fd)??''),undefined,{numeric:true})*(sort.dir==='desc'?-1:1));} return rows;
}
function ensureViews(s){ let vs=state.views.filter(v=>v.schemaId===s.id); if(!vs.length){state.views.push({id:uid('view'),schemaId:s.id,name:'Table',type:'table',filters:[],sorts:[],groupBy:'',visibleFields:s.fields.map(f=>f.id),createdAt:now()});vs=state.views.filter(v=>v.schemaId===s.id);scheduleSave();} return vs; }

function ensureNav(){
  $('#workspaceV020')?.remove(); if($('#workspaceV021'))return; const docs=$('.navItem[data-view="documents"]'); if(!docs)return; const btn=document.createElement('button');btn.className='navItem';btn.id='workspaceV021';btn.type='button';btn.innerHTML='<i class="fi fi-rr-apps"></i><span>Workspace</span>';docs.insertAdjacentElement('afterend',btn);
}
function setActiveNav(){ $$('.navItem').forEach(n=>n.classList.remove('active'));$('#workspaceV021')?.classList.add('active'); }
function setHeader(){ const t=$('#pageTitle'),s=$('#pageSubtitle'),ctx=$('#aiContext');if(t)t.textContent='Workspace';if(s)s.textContent='Universal data, automation, AI context, platform and governance.';if(ctx)ctx.textContent='Context: Universal workspace'; }
function tabs(){ const items=[['overview','Overview'],['data','Data'],['automations','Automations'],['intelligence','AI & Context'],['platform','Platform'],['governance','Governance'],['audit','Audit']];return `<div class="tabs v21Tabs">${items.map(([id,label])=>`<button class="tab ${activeTab===id?'active':''}" data-v21-tab="${id}">${label}</button>`).join('')}</div>`; }

function metrics(){
  const rec=state.objects.filter(o=>o.type==='record').length, goals=state.objects.filter(o=>o.type==='goal'), avg=goals.length?Math.round(goals.reduce((n,g)=>n+num(g.values?.progress),0)/goals.length):0;
  return `<div class="grid metrics v21Metrics"><article class="card metric"><div class="metricLabel"><span>Objects</span></div><div class="metricValue"><strong>${state.objects.length}</strong><span class="chip good">Graph</span></div><p>${rec} structured records</p></article><article class="card metric"><div class="metricLabel"><span>Schemas</span></div><div class="metricValue"><strong>${state.schemas.length}</strong><span class="chip good">Typed</span></div><p>${state.schemas.reduce((n,s)=>n+s.fields.length,0)} properties</p></article><article class="card metric"><div class="metricLabel"><span>Automations</span></div><div class="metricValue"><strong>${state.automations.length}</strong><span class="chip good">Runtime</span></div><p>${state.approvals.filter(a=>a.status==='pending').length} approvals pending</p></article><article class="card metric"><div class="metricLabel"><span>Goals</span></div><div class="metricValue"><strong>${goals.length}</strong><span class="chip good">${avg}%</span></div><p>Average progress</p></article></div>`;
}
function roadmapProgress(){
  const areas=[['Universal data','Typed properties, relations, rollups, formulas, six views, forms, dashboards',true],['Automation','Triggers, conditions, actions, approvals, schedules, webhooks',true],['Agent core','Context Spaces, instructions, skills, plans, citations',true],['Platform','Local API, connector SDK model, webhooks and MCP endpoint',true],['Specialists','Researcher, Analyst, Meetings and People local workflows',true],['Enterprise','Agent Builder, governance and audit',true],['External providers','Production connectors/models require credentials',false],['Computer Use','Adapter reserved; isolated execution runtime still required',false]];
  return `<article class="card sectionCard"><div class="sectionHead"><div><h3>Roadmap delivery</h3><p>V0.21 consolidates the roadmap into one local/platform foundation.</p></div><span class="chip good">Next architecture</span></div><div class="v21Roadmap">${areas.map(a=>`<div><span class="v21Dot ${a[2]?'done':'gate'}"></span><div><b>${esc(a[0])}</b><small>${esc(a[1])}</small></div><em>${a[2]?'Built':'External gate'}</em></div>`).join('')}</div></article>`;
}
function globalSearchCard(){return `<article class="card sectionCard"><div class="sectionHead"><div><h3>Permission-aware object search</h3><p>Lexical index across the V0.21 universal object graph with internal citations.</p></div></div><div class="v21Search"><input id="v21SearchInput" placeholder="Search records, goals, reports, meetings and agent artifacts"><button class="secondary" data-v21-search>Search</button></div><div id="v21SearchResults" class="v21SearchResults"><div class="empty">Search the universal workspace graph.</div></div></article>`;}
function overview(){ return `${metrics()}<div class="grid twoCol v21Overview">${roadmapProgress()}${globalSearchCard()}</div><div class="grid twoCol v21Overview"><article class="card sectionCard"><div class="sectionHead"><div><h3>Context graph</h3><p>Everything can reference everything else through stable object IDs.</p></div></div><div class="v21GraphStats"><b>${state.objects.reduce((n,o)=>n+(o.relations?.length||0),0)} explicit relations</b><span>${state.contexts.length} Context Spaces · ${state.comments.length} comments · ${state.citations.length} citations</span></div></article><article class="card sectionCard"><div class="sectionHead"><div><h3>Quick actions</h3><p>Create the next structured layer.</p></div></div><div class="v21Quick"><button class="secondary" data-v21-new-schema>+ Database</button><button class="secondary" data-v21-new-context>+ Context Space</button><button class="secondary" data-v21-new-automation>+ Automation</button><button class="secondary" data-v21-export>Export workspace</button></div></article></div>`; }

function dataPage(){
  const dashboards=state.dashboards.map(d=>`<article class="card v21MiniCard"><div><h3>${esc(d.name)}</h3><p>${d.widgets?.length||0} widgets</p></div><button class="miniButton" data-v21-dashboard-open="${d.id}">Open</button></article>`).join('')||'<div class="empty">No dashboards yet.</div>';
  return `<div class="v21Toolbar"><div><b>Universal Data Platform</b><span>Typed schemas, object relations, formulas, views, forms and dashboards.</span></div><div><button class="secondary" data-v21-new-dashboard>+ Dashboard</button><button class="primary" data-v21-new-schema><i class="fi fi-rr-plus"></i> Database</button></div></div><div class="v21Grid">${state.schemas.map(s=>`<article class="card v21SchemaCard"><div class="v21CardHead"><div><span class="v21Kicker">${s.fields.length} typed properties</span><h3>${esc(s.name)}</h3><p>${esc(s.description||'Universal Qanteak schema')}</p></div><span class="chip good">${records(s.id).length} records</span></div><div class="v21FieldChips">${s.fields.slice(0,7).map(f=>`<span>${esc(f.label)} · ${esc(f.type)}</span>`).join('')}${s.fields.length>7?`<span>+${s.fields.length-7}</span>`:''}</div><div class="v21Actions"><button class="miniButton" data-v21-schema-open="${s.id}">Open</button><button class="miniButton" data-v21-record-new="${s.id}">Add record</button><button class="miniButton" data-v21-form-new="${s.id}">Form</button></div></article>`).join('')}</div><div class="v21SectionHead"><div><b>Dashboards</b><span>Compose KPIs and charts from workspace data.</span></div></div><div class="v21Grid">${dashboards}</div>`;
}

function automationPage(){
  const approvals=state.approvals.filter(a=>a.status==='pending').map(a=>`<article class="card v21Approval"><div><span class="v21Kicker">${esc(a.kind||'approval')}</span><h3>${esc(a.title)}</h3><p>${esc(a.detail||'Confirmation required')}</p></div><div class="v21Actions"><button class="miniButton" data-v21-approval-approve="${a.id}">Approve</button><button class="miniButton" data-v21-approval-reject="${a.id}">Reject</button></div></article>`).join('')||'<div class="empty">No pending approvals.</div>';
  return `<div class="v21Toolbar"><div><b>Automation Platform</b><span>Trigger → Conditions → Actions → Approval → Result.</span></div><button class="primary" data-v21-new-automation><i class="fi fi-rr-plus"></i> Automation</button></div><div class="v21Grid">${state.automations.map(a=>`<article class="card v21AutoCard"><div class="v21CardHead"><div><span class="v21Kicker">${esc(a.trigger?.type||'manual')} trigger</span><h3>${esc(a.name)}</h3><p>${esc(automationSummary(a))}</p></div><span class="chip ${a.enabled?'good':'warn'}">${a.enabled?'Enabled':'Paused'}</span></div><div class="v21Actions"><button class="miniButton" data-v21-auto-run="${a.id}">Run now</button><button class="miniButton" data-v21-auto-toggle="${a.id}">${a.enabled?'Pause':'Enable'}</button><button class="miniButton" data-v21-auto-delete="${a.id}">Delete</button></div><small>Last run: ${a.lastRunAt?esc(fmtTime(a.lastRunAt)):'Never'} · ${Number(a.runCount||0)} runs</small></article>`).join('')||'<div class="empty">No automations yet.</div>'}</div><div class="v21SectionHead"><div><b>Approval queue</b><span>Writes and external actions can be confirmation-gated.</span></div></div><div class="v21Grid">${approvals}</div>`;
}
function automationSummary(a){ const action=a.action||{};return `${a.condition?.fieldId?'Conditional · ':''}${action.type||'log'}${action.schemaId?` → ${schema(action.schemaId)?.name||'database'}`:''}`; }

function intelligencePage(){
  const contexts=state.contexts.map(c=>`<article class="card v21ContextCard"><div><span class="v21Kicker">Context Space</span><h3>${esc(c.name)}</h3><p>${(c.objectIds||[]).length} objects · ${(c.links||[]).length} links</p></div><div class="v21Actions"><button class="miniButton" data-v21-context-open="${c.id}">Open</button><button class="miniButton" data-v21-research-context="${c.id}">Research</button></div></article>`).join('')||'<div class="empty">Create a focused Context Space for Qanteak AI.</div>';
  const agents=state.agents.map(a=>`<article class="card v21AgentCard"><div><span class="v21Kicker">Custom agent</span><h3>${esc(a.name)}</h3><p>${esc(a.purpose||a.instructions||'Configured Qanteak agent')}</p></div><div class="v21Actions"><button class="miniButton" data-v21-agent-run="${a.id}">Run</button><button class="miniButton" data-v21-agent-delete="${a.id}">Delete</button></div></article>`).join('')||'<div class="empty">Build reusable agents with scoped context and tools.</div>';
  return `<div class="v21Toolbar"><div><b>Qanteak Context + Agent Core</b><span>Focused context, reusable skills, specialist workflows and auditable plans.</span></div><div><button class="secondary" data-v21-new-skill>+ Skill</button><button class="secondary" data-v21-new-agent>+ Agent</button><button class="primary" data-v21-new-context>+ Context Space</button></div></div><div class="v21Grid">${contexts}</div><div class="v21SectionHead"><div><b>Specialist Intelligence</b><span>Local deterministic workflows now; model-backed execution can plug in later.</span></div></div><div class="v21Specialists"><button data-v21-specialist="researcher"><i class="fi fi-rr-search-alt"></i><b>Researcher</b><span>Build cited reports from Qanteak context.</span></button><button data-v21-specialist="analyst"><i class="fi fi-rr-chart-histogram"></i><b>Analyst</b><span>Aggregate structured numeric data.</span></button><button data-v21-specialist="meeting"><i class="fi fi-rr-microphone"></i><b>Meeting Intelligence</b><span>Extract decisions and actions from notes/transcripts.</span></button><button data-v21-specialist="people"><i class="fi fi-rr-users"></i><b>People Intelligence</b><span>Find ownership and workspace expertise.</span></button></div><div class="v21SectionHead"><div><b>Skills</b><span>Versioned repeatable instructions.</span></div></div><div class="v21Grid">${state.skills.map(s=>`<article class="card v21MiniCard"><div><h3>${esc(s.name)}</h3><p>${esc(s.instructions||'Reusable skill')}</p></div><span class="chip good">v${s.version||1}</span></article>`).join('')||'<div class="empty">No custom skills yet.</div>'}</div><div class="v21SectionHead"><div><b>Agent Builder</b><span>Instructions + context + skills + tools + confirmation policy.</span></div></div><div class="v21Grid">${agents}</div>`;
}

function connectorRows(){return CONNECTOR_CATALOG.map(([id,name,scope,gate])=>{const saved=state.connectors.find(c=>c.id===id);return `<article class="card v21Connector"><div><span class="v21Kicker">${saved?.enabled?'Enabled adapter':'Connector SDK'}</span><h3>${esc(name)}</h3><p>${esc(scope)} · ${esc(gate)}</p></div><span class="chip ${saved?.enabled?'good':'warn'}">${saved?.enabled?'Configured':'Adapter ready'}</span></article>`;}).join('');}
function platformPage(){
  return `<div class="v21Toolbar"><div><b>Platform & Connectors</b><span>Local API, MCP tool endpoint, webhooks, connector contracts and import/export.</span></div><button class="secondary" data-v21-api-toggle>${apiStatus.enabled?'Disable local API':'Enable local API'}</button></div><div class="grid twoCol v21Overview"><article class="card sectionCard"><div class="sectionHead"><div><h3>Local API + MCP</h3><p>Bound to 127.0.0.1 and bearer-token protected.</p></div><span class="chip ${apiStatus.enabled?'good':'warn'}">${apiStatus.enabled?'Running':'Off'}</span></div><div class="v21PlatformStatus"><b>${esc(apiStatus.baseUrl||'http://127.0.0.1:32145')}</b><span>MCP: ${esc(apiStatus.mcpPath||'/mcp')}</span>${apiStatus.enabled?`<code>${esc(apiStatus.token)}</code>`:'<small>Token is only exposed while the local API is enabled.</small>'}</div></article><article class="card sectionCard"><div class="sectionHead"><div><h3>Import / export</h3><p>Portable JSON plus CSV and Markdown ingestion.</p></div></div><div class="v21Quick"><button class="secondary" data-v21-export>Export JSON</button><button class="secondary" data-v21-import>Import file</button><button class="secondary" data-v21-connector-manifest>Connector manifest</button></div></article></div><div class="v21SectionHead"><div><b>Connector catalog</b><span>Common contract is built; credentialed providers remain external configuration.</span></div></div><div class="v21Grid">${connectorRows()}</div><div class="v21SectionHead"><div><b>Outbound webhooks</b><span>HTTPS delivery from the Electron main process, governed by approval settings.</span></div><button class="secondary" data-v21-new-webhook>+ Webhook</button></div><div class="v21Grid">${state.webhooks.map(w=>`<article class="card v21MiniCard"><div><h3>${esc(w.name)}</h3><p>${esc(w.event)} · ${esc(w.url)}</p></div><span class="chip ${w.enabled?'good':'warn'}">${w.enabled?'Enabled':'Paused'}</span></article>`).join('')||'<div class="empty">No outbound webhooks configured.</div>'}</div>`;
}

function governancePage(){
  const g=state.governance;
  return `<div class="v21Toolbar"><div><b>Enterprise Governance</b><span>Agent/tool permissions, confirmation policy, data controls and safe external-action gates.</span></div><button class="primary" data-v21-governance-save>Save governance</button></div><div class="grid twoCol v21Overview"><article class="card sectionCard"><div class="sectionHead"><div><h3>Agent instructions</h3><p>Persistent workspace and user-level behavior.</p></div></div><label class="v21Field"><span>Workspace instructions</span><textarea id="v21WorkspaceInstructions" rows="6">${esc(state.instructions.workspace||'')}</textarea></label><label class="v21Field"><span>User instructions</span><textarea id="v21UserInstructions" rows="5">${esc(state.instructions.user||'')}</textarea></label></article><article class="card sectionCard"><div class="sectionHead"><div><h3>Safety & approvals</h3><p>Writes, external actions and tools stay observable.</p></div></div><label class="v21Check"><input id="v21RequireApproval" type="checkbox" ${g.requireApprovalForWrites?'checked':''}><span>Require approval for agent/automation writes</span></label><label class="v21Check"><input id="v21ExternalActions" type="checkbox" ${g.externalActionsEnabled?'checked':''}><span>Allow approved external webhook actions</span></label><label class="v21Field"><span>Retention (days)</span><input id="v21Retention" type="number" min="1" max="3650" value="${Number(g.retentionDays||365)}"></label><div class="v21SafetyGate"><b>Computer Use</b><span>Not enabled in V0.21. The adapter is intentionally blocked until Qanteak has a hardened isolated runtime, credential isolation and screenshot/action auditing.</span></div></article></div><article class="card sectionCard"><div class="sectionHead"><div><h3>Allowed agent tools</h3><p>Least-privilege tool policy.</p></div></div><div class="v21ToolChecks">${['search','read','create_object','update_object','run_automation','send_webhook','external_connector'].map(t=>`<label class="v21Check"><input type="checkbox" data-v21-tool="${t}" ${(g.allowedTools||[]).includes(t)?'checked':''}><span>${esc(t)}</span></label>`).join('')}</div></article>`;
}
function auditPage(){return `<article class="card sectionCard"><div class="sectionHead"><div><h3>Audit & observability</h3><p>Local immutable-style activity history for V0.21 platform operations.</p></div><button class="secondary" data-v21-audit-export>Export audit</button></div><div class="v21Audit">${state.audit.slice(0,300).map(a=>`<div><span><b>${esc(a.action)}</b><small>${esc(a.detail||'Qanteak workspace')}</small></span><em>${esc(a.actor||'local-user')}</em><time>${esc(fmtTime(a.at))}</time></div>`).join('')||'<div class="empty">No audit events yet.</div>'}</div></article>`;}
function page(){return activeTab==='data'?dataPage():activeTab==='automations'?automationPage():activeTab==='intelligence'?intelligencePage():activeTab==='platform'?platformPage():activeTab==='governance'?governancePage():activeTab==='audit'?auditPage():overview();}
function render(){ ensureNav();setActiveNav();setHeader();const content=$('#content');if(!content)return;content.innerHTML=`${tabs()}<div class="v21Workspace">${page()}</div>`; }

function modal(title,body,actions=''){
  let host=$('#v21Modal');if(!host){host=document.createElement('section');host.id='v21Modal';host.className='v21Modal';document.body.append(host);}host.innerHTML=`<div class="v21ModalCard"><div class="panelHead"><div><h3>${esc(title)}</h3><p>${RELEASE} universal workspace</p></div><button type="button" data-v21-close>×</button></div><div class="v21ModalBody">${body}</div>${actions}</div>`;host.classList.add('open');
}
function closeModal(){$('#v21Modal')?.classList.remove('open');currentSchemaId=null;}

function newSchemaModal(){modal('New database',`<div class="v21FormGrid"><label class="v21Field span2"><span>Name</span><input id="v21SchemaName" value="Team database" required></label><label class="v21Field span2"><span>Description</span><input id="v21SchemaDesc" value="Universal Qanteak database"></label></div>`,`<div class="formActions"><button class="secondary" data-v21-close>Cancel</button><button class="primary" data-v21-schema-create>Create database</button></div>`);}
async function createSchema(){const name=$('#v21SchemaName')?.value.trim();if(!name)return;const s={id:uid('schema'),name,description:$('#v21SchemaDesc')?.value.trim()||'',fields:defaultFields(),createdAt:now(),updatedAt:now()};state.schemas.push(s);state.views.push({id:uid('view'),schemaId:s.id,name:'Table',type:'table',filters:[],sorts:[],groupBy:'',visibleFields:s.fields.map(f=>f.id),createdAt:now()});audit('Database created',name);await platformSave();closeModal();activeTab='data';render();}
function propertyModal(schemaId){const s=schema(schemaId);if(!s)return;currentSchemaId=s.id;modal(`Add property · ${s.name}`,`<div class="v21FormGrid"><label class="v21Field"><span>Property name</span><input id="v21PropName" value="New property"></label><label class="v21Field"><span>Type</span><select id="v21PropType">${PROPERTY_TYPES.map(t=>`<option value="${t}">${t}</option>`).join('')}</select></label><label class="v21Field span2"><span>Options / formula / target notes</span><input id="v21PropConfig" placeholder="Status options comma-separated, or formula like PROP(&quot;Budget&quot;)-PROP(&quot;Cost&quot;)"></label></div><div class="v21Hint">Relations can target all Qanteak objects. Rollup configuration is completed after creation.</div>`,`<div class="formActions"><button class="secondary" data-v21-close>Cancel</button><button class="primary" data-v21-property-create="${s.id}">Add property</button></div>`);}
async function createProperty(schemaId){const s=schema(schemaId),label=$('#v21PropName')?.value.trim(),type=$('#v21PropType')?.value,config=$('#v21PropConfig')?.value.trim()||'';if(!s||!label)return;const f=field(type,label);if(['status','select','multi_select'].includes(type))f.options=config?config.split(',').map(x=>x.trim()).filter(Boolean):['New','In progress','Done'];if(type==='formula')f.formula=config||'PROP("Name")';if(type==='currency')f.currency='USD';if(type==='relation')f.target='any';s.fields.push(f);s.updatedAt=now();for(const v of state.views.filter(v=>v.schemaId===s.id))v.visibleFields=[...(v.visibleFields||[]),f.id];audit('Property added',`${s.name} · ${label} (${type})`);await platformSave();closeModal();openSchema(s.id);}

function fieldInput(s,f,value=''){
  const id=`v21val_${f.id}`, val=value??'';
  if(['created_time','created_by','edited_time','edited_by','unique_id','rollup','formula','button'].includes(f.type))return `<label class="v21Field"><span>${esc(f.label)}</span><input disabled value="Computed"></label>`;
  if(f.type==='checkbox')return `<label class="v21Check"><input id="${id}" data-field="${f.id}" type="checkbox" ${val?'checked':''}><span>${esc(f.label)}</span></label>`;
  if(f.type==='date')return `<label class="v21Field"><span>${esc(f.label)}</span><input id="${id}" data-field="${f.id}" type="date" value="${esc(String(val).slice(0,10))}"></label>`;
  if(['number','currency','percentage'].includes(f.type))return `<label class="v21Field"><span>${esc(f.label)}</span><input id="${id}" data-field="${f.id}" type="number" step="any" value="${esc(val)}"></label>`;
  if(['status','select'].includes(f.type))return `<label class="v21Field"><span>${esc(f.label)}</span><select id="${id}" data-field="${f.id}"><option value=""></option>${(f.options||[]).map(o=>`<option ${String(val)===o?'selected':''}>${esc(o)}</option>`).join('')}</select></label>`;
  if(f.type==='multi_select')return `<label class="v21Field"><span>${esc(f.label)} (comma-separated)</span><input id="${id}" data-field="${f.id}" value="${esc(Array.isArray(val)?val.join(', '):val)}"></label>`;
  if(f.type==='relation'){const options=state.objects.filter(o=>o.type==='record').map(o=>`<option value="${o.id}" ${relationTargets(val).includes(o.id)?'selected':''}>${esc(objectTitle(o))}</option>`).join('');return `<label class="v21Field"><span>${esc(f.label)} relation</span><select id="${id}" data-field="${f.id}" multiple size="4">${options}</select></label>`;}
  const type=f.type==='email'?'email':f.type==='url'?'url':f.type==='phone'?'tel':'text';return `<label class="v21Field"><span>${esc(f.label)}</span><input id="${id}" data-field="${f.id}" type="${type}" value="${esc(val)}"></label>`;
}
function recordModal(schemaId,recordId=''){const s=schema(schemaId),r=recordId?object(recordId):null;if(!s)return;currentSchemaId=s.id;modal(r?`Edit record · ${s.name}`:`Add record · ${s.name}`,`<div class="v21FormGrid">${s.fields.map(f=>fieldInput(s,f,r?.values?.[f.id])).join('')}</div>`,`<div class="formActions"><button class="secondary" data-v21-close>Cancel</button><button class="primary" data-v21-record-save="${s.id}" data-record-id="${r?.id||''}">${r?'Save changes':'Create record'}</button></div>`);}
function readFieldValue(el,f){if(f.type==='checkbox')return el.checked;if(f.type==='relation')return [...el.selectedOptions].map(o=>o.value);if(f.type==='multi_select')return el.value.split(',').map(x=>x.trim()).filter(Boolean);if(['number','currency','percentage'].includes(f.type))return el.value===''?'':Number(el.value);return el.value;}
async function saveRecord(schemaId,recordId=''){const s=schema(schemaId);if(!s)return;const values={};for(const f of s.fields){const el=$(`#v21val_${CSS.escape(f.id)}`);if(el&&!el.disabled)values[f.id]=readFieldValue(el,f);}const nf=nameField(s),title=String(values[nf?.id]||'Untitled');let r=recordId?object(recordId):null;if(r){r.values=values;r.title=title;r.updatedAt=now();r.editedBy='Local user';audit('Record updated',`${s.name} · ${title}`);}else{r={id:uid('obj'),type:'record',schemaId:s.id,title,values,relations:[],owner:'Local user',createdBy:'Local user',editedBy:'Local user',source:'qanteak',createdAt:now(),updatedAt:now()};state.objects.push(r);audit('Record created',`${s.name} · ${title}`);await emitEvent('object.created',{object:r,schema:s});}await platformSave();closeModal();openSchema(s.id);}

function viewButtons(s,active){return ['table','board','calendar','timeline','list','gallery'].map(t=>`<button class="tab ${active===t?'active':''}" data-v21-view-type="${t}" data-schema-id="${s.id}">${t[0].toUpperCase()+t.slice(1)}</button>`).join('');}
function getView(s,type){let v=state.views.find(v=>v.schemaId===s.id&&v.type===type);if(!v){v={id:uid('view'),schemaId:s.id,name:type[0].toUpperCase()+type.slice(1),type,filters:[],sorts:[],groupBy:'',visibleFields:s.fields.map(f=>f.id),createdAt:now()};state.views.push(v);scheduleSave();}return v;}
function tableView(s,v){const rows=filteredRecords(s,v),fields=(v.visibleFields||s.fields.map(f=>f.id)).map(id=>s.fields.find(f=>f.id===id)).filter(Boolean);return `<div class="v21Table"><div class="v21Tr v21Th">${fields.map(f=>`<span>${esc(f.label)}</span>`).join('')}<span></span></div>${rows.map(r=>`<div class="v21Tr">${fields.map(f=>`<span>${esc(displayValue(r,s,f))}</span>`).join('')}<span><button class="miniButton" data-v21-record-edit="${r.id}" data-schema-id="${s.id}">Edit</button><button class="miniButton" data-v21-thread="${r.id}">Thread</button></span></div>`).join('')||'<div class="empty">No records yet.</div>'}</div>`;}
function groupFieldFor(s,v){return s.fields.find(f=>f.id===v.groupBy)||s.fields.find(f=>['status','select'].includes(f.type));}
function boardView(s,v){const rows=filteredRecords(s,v),gf=groupFieldFor(s,v);if(!gf)return'<div class="empty">Add a Status/Select field for Board grouping.</div>';const groups=[...new Set(rows.map(r=>String(computedValue(r,s,gf)||'Unsorted')))];return `<div class="v21Board">${groups.map(g=>`<div class="v21BoardCol"><div class="v21BoardHead">${esc(g)} <span>${rows.filter(r=>String(computedValue(r,s,gf)||'Unsorted')===g).length}</span></div>${rows.filter(r=>String(computedValue(r,s,gf)||'Unsorted')===g).map(r=>`<article class="v21BoardCard"><b>${esc(objectTitle(r))}</b><span>${esc(r.owner||'Local user')}</span><button class="miniButton" data-v21-record-edit="${r.id}" data-schema-id="${s.id}">Open</button></article>`).join('')}</div>`).join('')}</div>`;}
function dateFieldFor(s){return s.fields.find(f=>f.type==='date');}
function calendarView(s,v,timeline=false){const df=dateFieldFor(s);if(!df)return'<div class="empty">Add a Date property to use this view.</div>';const rows=filteredRecords(s,v).filter(r=>computedValue(r,s,df)).sort((a,b)=>String(computedValue(a,s,df)).localeCompare(String(computedValue(b,s,df))));return `<div class="${timeline?'v21Timeline':'v21Calendar'}">${rows.map(r=>`<div class="v21CalendarRow"><time>${esc(fmtDate(computedValue(r,s,df)))}</time><div><b>${esc(objectTitle(r))}</b><span>${esc(displayValue(r,s,groupFieldFor(s,v)||df))}</span></div><button class="miniButton" data-v21-record-edit="${r.id}" data-schema-id="${s.id}">Open</button></div>`).join('')||'<div class="empty">No dated records.</div>'}</div>`;}
function listView(s,v){return `<div class="v21List">${filteredRecords(s,v).map(r=>`<button data-v21-record-edit="${r.id}" data-schema-id="${s.id}"><b>${esc(objectTitle(r))}</b><span>${s.fields.slice(1,4).map(f=>esc(displayValue(r,s,f))).join(' · ')}</span></button>`).join('')||'<div class="empty">No records.</div>'}</div>`;}
function galleryView(s,v){return `<div class="v21Gallery">${filteredRecords(s,v).map(r=>`<article><div class="v21GalleryArt">${esc(objectTitle(r).slice(0,2).toUpperCase())}</div><b>${esc(objectTitle(r))}</b><span>${s.fields.slice(1,3).map(f=>esc(displayValue(r,s,f))).join(' · ')}</span><button class="miniButton" data-v21-record-edit="${r.id}" data-schema-id="${s.id}">Open</button></article>`).join('')||'<div class="empty">No records.</div>'}</div>`;}
function renderSchemaView(s,type){const v=getView(s,type);if(type==='table')return tableView(s,v);if(type==='board')return boardView(s,v);if(type==='calendar')return calendarView(s,v);if(type==='timeline')return calendarView(s,v,true);if(type==='list')return listView(s,v);return galleryView(s,v);}
function openSchema(id,type='table'){const s=schema(id);if(!s)return;currentSchemaId=s.id;const forms=state.forms.filter(f=>f.schemaId===s.id);modal(s.name,`<div class="v21SchemaModalTop"><div class="tabs">${viewButtons(s,type)}</div><div class="v21Actions"><button class="miniButton" data-v21-property-new="${s.id}">+ Property</button><button class="miniButton" data-v21-record-new="${s.id}">+ Record</button><button class="miniButton" data-v21-form-new="${s.id}">+ Form</button><button class="miniButton" data-v21-view-config="${s.id}" data-view-type="${type}">View settings</button></div></div><div class="v21SchemaMeta">${s.fields.map(f=>`<span title="${esc(f.id)}">${esc(f.label)} · ${esc(f.type)}</span>`).join('')}</div><div id="v21SchemaView">${renderSchemaView(s,type)}</div>${forms.length?`<div class="v21ModalSection"><b>Forms</b>${forms.map(f=>`<button class="miniButton" data-v21-form-open="${f.id}">${esc(f.name)}</button>`).join(' ')}</div>`:''}`);}
function viewConfigModal(schemaId,type){const s=schema(schemaId),v=getView(s,type);modal(`View settings · ${s.name}`,`<div class="v21FormGrid"><label class="v21Field"><span>Group by</span><select id="v21GroupBy"><option value="">Automatic</option>${s.fields.map(f=>`<option value="${f.id}" ${v.groupBy===f.id?'selected':''}>${esc(f.label)}</option>`).join('')}</select></label><label class="v21Field"><span>Sort field</span><select id="v21SortField"><option value="">None</option>${s.fields.map(f=>`<option value="${f.id}" ${v.sorts?.[0]?.fieldId===f.id?'selected':''}>${esc(f.label)}</option>`).join('')}</select></label><label class="v21Field"><span>Sort direction</span><select id="v21SortDir"><option value="asc">Ascending</option><option value="desc" ${v.sorts?.[0]?.dir==='desc'?'selected':''}>Descending</option></select></label><label class="v21Field"><span>Filter field</span><select id="v21FilterField"><option value="">None</option>${s.fields.map(f=>`<option value="${f.id}" ${v.filters?.[0]?.fieldId===f.id?'selected':''}>${esc(f.label)}</option>`).join('')}</select></label><label class="v21Field"><span>Filter operator</span><select id="v21FilterOp">${['contains','equals','not_equals','gt','lt','empty'].map(o=>`<option ${v.filters?.[0]?.op===o?'selected':''}>${o}</option>`).join('')}</select></label><label class="v21Field"><span>Filter value</span><input id="v21FilterValue" value="${esc(v.filters?.[0]?.value||'')}"></label></div>`,`<div class="formActions"><button class="secondary" data-v21-close>Cancel</button><button class="primary" data-v21-view-save="${v.id}" data-schema-id="${s.id}">Save view</button></div>`);}
async function saveView(viewId,schemaId){const v=state.views.find(x=>x.id===viewId);if(!v)return;v.groupBy=$('#v21GroupBy')?.value||'';const sf=$('#v21SortField')?.value;v.sorts=sf?[{fieldId:sf,dir:$('#v21SortDir')?.value||'asc'}]:[];const ff=$('#v21FilterField')?.value;v.filters=ff?[{fieldId:ff,op:$('#v21FilterOp')?.value||'contains',value:$('#v21FilterValue')?.value||''}]:[];audit('View configured',`${schema(schemaId)?.name} · ${v.type}`);await platformSave();closeModal();openSchema(schemaId,v.type);}

function formNewModal(schemaId){const s=schema(schemaId);if(!s)return;modal(`Create form · ${s.name}`,`<div class="v21FormGrid"><label class="v21Field span2"><span>Form name</span><input id="v21FormName" value="${esc(s.name)} form"></label><label class="v21Field span2"><span>Description</span><input id="v21FormDesc" value="Submit directly into ${esc(s.name)}"></label></div>`,`<div class="formActions"><button class="secondary" data-v21-close>Cancel</button><button class="primary" data-v21-form-create="${s.id}">Create form</button></div>`);}
async function createForm(schemaId){const s=schema(schemaId),name=$('#v21FormName')?.value.trim();if(!s||!name)return;state.forms.push({id:uid('form'),schemaId:s.id,name,description:$('#v21FormDesc')?.value.trim()||'',fieldIds:s.fields.filter(f=>!['formula','rollup','created_time','created_by','edited_time','edited_by','unique_id','button'].includes(f.type)).map(f=>f.id),access:'workspace',createdAt:now()});audit('Form created',name);await platformSave();closeModal();openForm(state.forms.at(-1).id);}
function openForm(id){const f=state.forms.find(x=>x.id===id),s=schema(f?.schemaId);if(!f||!s)return;modal(f.name,`<p>${esc(f.description||'')}</p><div class="v21FormGrid">${f.fieldIds.map(id=>s.fields.find(x=>x.id===id)).filter(Boolean).map(fd=>fieldInput(s,fd)).join('')}</div>`,`<div class="formActions"><button class="secondary" data-v21-close>Cancel</button><button class="primary" data-v21-form-submit="${f.id}">Submit</button></div>`);}
async function submitForm(formId){const f=state.forms.find(x=>x.id===formId),s=schema(f?.schemaId);if(!f||!s)return;const values={};for(const id of f.fieldIds){const fd=s.fields.find(x=>x.id===id),el=$(`#v21val_${CSS.escape(id)}`);if(fd&&el)values[id]=readFieldValue(el,fd);}const nf=nameField(s),r={id:uid('obj'),type:'record',schemaId:s.id,title:String(values[nf?.id]||'Form response'),values,relations:[],owner:'Form submission',createdBy:'Form',editedBy:'Form',source:`form:${f.id}`,createdAt:now(),updatedAt:now()};state.objects.push(r);audit('Form submitted',`${f.name} · ${r.title}`);await emitEvent('form.submitted',{form:f,object:r,schema:s});await platformSave();closeModal();toast('Form submitted into the database.');render();}

function dashboardNewModal(){modal('New dashboard',`<div class="v21FormGrid"><label class="v21Field span2"><span>Name</span><input id="v21DashboardName" value="Executive dashboard"></label><label class="v21Field"><span>Source database</span><select id="v21DashboardSchema">${state.schemas.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select></label><label class="v21Field"><span>Widget</span><select id="v21DashboardWidget"><option value="count">Record count</option><option value="sum">Numeric sum</option><option value="status">Status distribution</option></select></label></div>`,`<div class="formActions"><button class="secondary" data-v21-close>Cancel</button><button class="primary" data-v21-dashboard-create>Create dashboard</button></div>`);}
async function createDashboard(){const name=$('#v21DashboardName')?.value.trim(),schemaId=$('#v21DashboardSchema')?.value,kind=$('#v21DashboardWidget')?.value;if(!name||!schemaId)return;state.dashboards.push({id:uid('dash'),name,widgets:[{id:uid('widget'),kind,schemaId}],createdAt:now()});audit('Dashboard created',name);await platformSave();closeModal();render();}
function dashboardWidget(w){const s=schema(w.schemaId),rows=records(w.schemaId);if(!s)return'';if(w.kind==='count')return `<article><span>${esc(s.name)}</span><strong>${rows.length}</strong><small>records</small></article>`;if(w.kind==='sum'){const nf=s.fields.find(f=>['number','currency','percentage'].includes(f.type)),total=nf?rows.reduce((n,r)=>n+num(computedValue(r,s,nf)),0):0;return `<article><span>${esc(nf?.label||'Numeric total')}</span><strong>${total.toLocaleString()}</strong><small>${esc(s.name)}</small></article>`;}const sf=s.fields.find(f=>['status','select'].includes(f.type)),groups={};for(const r of rows){const k=String(computedValue(r,s,sf)||'Unsorted');groups[k]=(groups[k]||0)+1;}const max=Math.max(1,...Object.values(groups));return `<article class="v21Chart"><span>${esc(sf?.label||'Status')}</span>${Object.entries(groups).map(([k,v])=>`<div><b>${esc(k)}</b><i style="width:${Math.round(v/max*100)}%"></i><em>${v}</em></div>`).join('')}</article>`;}
function openDashboard(id){const d=state.dashboards.find(x=>x.id===id);if(!d)return;modal(d.name,`<div class="v21Dashboard">${(d.widgets||[]).map(dashboardWidget).join('')}</div>`);}

function automationModal(){modal('New automation',`<div class="v21FormGrid"><label class="v21Field span2"><span>Name</span><input id="v21AutoName" value="Workspace automation"></label><label class="v21Field"><span>Trigger</span><select id="v21AutoTrigger"><option value="manual">Manual</option><option value="object.created">Object created</option><option value="form.submitted">Form submitted</option><option value="schedule">Recurring schedule</option></select></label><label class="v21Field"><span>Every N minutes (schedule)</span><input id="v21AutoMinutes" type="number" min="1" value="60"></label><label class="v21Field"><span>Condition field (optional)</span><select id="v21AutoConditionField"><option value="">None</option>${state.schemas.flatMap(s=>s.fields.map(f=>`<option value="${s.id}:${f.id}">${esc(s.name)} · ${esc(f.label)}</option>`)).join('')}</select></label><label class="v21Field"><span>Condition value</span><input id="v21AutoConditionValue"></label><label class="v21Field"><span>Action</span><select id="v21AutoAction"><option value="log">Log activity</option><option value="create_record">Create database record</option><option value="queue_approval">Create approval</option><option value="webhook">Send webhook</option></select></label><label class="v21Field"><span>Target database</span><select id="v21AutoTarget"><option value="">None</option>${state.schemas.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select></label><label class="v21Field"><span>Webhook</span><select id="v21AutoWebhook"><option value="">None</option>${state.webhooks.map(w=>`<option value="${w.id}">${esc(w.name)}</option>`).join('')}</select></label></div>`,`<div class="formActions"><button class="secondary" data-v21-close>Cancel</button><button class="primary" data-v21-auto-create>Create automation</button></div>`);}
async function createAutomation(){const name=$('#v21AutoName')?.value.trim();if(!name)return;const cond=$('#v21AutoConditionField')?.value||'',parts=cond.split(':');state.automations.push({id:uid('auto'),name,enabled:true,trigger:{type:$('#v21AutoTrigger')?.value||'manual',intervalMinutes:Number($('#v21AutoMinutes')?.value||60)},condition:cond?{schemaId:parts[0],fieldId:parts[1],op:'equals',value:$('#v21AutoConditionValue')?.value||''}:null,action:{type:$('#v21AutoAction')?.value||'log',schemaId:$('#v21AutoTarget')?.value||'',webhookId:$('#v21AutoWebhook')?.value||''},runCount:0,lastRunAt:'',createdAt:now()});audit('Automation created',name);await platformSave();closeModal();render();}
function conditionMatches(a,payload){if(!a.condition)return true;const obj=payload?.object;if(!obj||obj.schemaId!==a.condition.schemaId)return false;const s=schema(obj.schemaId),f=s?.fields.find(x=>x.id===a.condition.fieldId);return String(computedValue(obj,s,f)??'')===String(a.condition.value??'');}
async function runAutomation(id,payload={source:'manual'}){const a=state.automations.find(x=>x.id===id);if(!a||!a.enabled)return;if(!conditionMatches(a,payload)){audit('Automation skipped',`${a.name} · condition not met`);return;}const action=a.action||{};if(action.type==='log')audit('Automation executed',a.name,'automation');
  else if(action.type==='create_record'){const s=schema(action.schemaId);if(s){const nf=nameField(s),obj={id:uid('obj'),type:'record',schemaId:s.id,title:`Automated ${new Date().toLocaleString()}`,values:{[nf.id]:`Automated ${new Date().toLocaleString()}`},relations:[],source:`automation:${a.id}`,owner:'Automation',createdAt:now(),updatedAt:now()};if(state.governance.requireApprovalForWrites)queueApproval('automation_write',`Approve ${a.name}`,`Create record in ${s.name}`,{type:'create_object',object:obj});else state.objects.push(obj);}}
  else if(action.type==='queue_approval')queueApproval('automation',`Approval from ${a.name}`,'Automation requested confirmation.',{type:'log',message:a.name});
  else if(action.type==='webhook'){const w=state.webhooks.find(x=>x.id===action.webhookId);if(w){const approval={type:'webhook',webhookId:w.id,payload:{event:'automation.run',automation:{id:a.id,name:a.name},source:payload.source||'manual',at:now()}};if(state.governance.requireApprovalForWrites||!state.governance.externalActionsEnabled)queueApproval('external_action',`Send webhook · ${w.name}`,w.url,approval);else await executeApprovalPayload(approval);}}
  a.lastRunAt=now();a.runCount=Number(a.runCount||0)+1;audit('Automation run',a.name,'automation');await platformSave();render();}
async function emitEvent(type,payload){for(const a of state.automations.filter(a=>a.enabled&&a.trigger?.type===type))await runAutomation(a.id,{...payload,source:type});for(const w of state.webhooks.filter(w=>w.enabled&&w.event===type)){const p={type:'webhook',webhookId:w.id,payload:{event:type,object:payload?.object?{id:payload.object.id,type:payload.object.type,title:objectTitle(payload.object)}:null,at:now()}};if(state.governance.requireApprovalForWrites||!state.governance.externalActionsEnabled)queueApproval('webhook',`Deliver ${type} webhook`,w.url,p);else await executeApprovalPayload(p);}}
function queueApproval(kind,title,detail,payload){state.approvals.unshift({id:uid('approval'),kind,title,detail,payload,status:'pending',createdAt:now()});audit('Approval queued',title,'system');scheduleSave();}
async function executeApprovalPayload(p){if(!p)return;if(p.type==='create_object'&&p.object)state.objects.push(p.object);else if(p.type==='webhook'){const w=state.webhooks.find(x=>x.id===p.webhookId);if(!w)throw new Error('Webhook not found');if(!state.governance.externalActionsEnabled)throw new Error('External actions are disabled by governance.');if(!window.qanteakDesktop?.platformSendWebhook)throw new Error('Webhook bridge unavailable.');await window.qanteakDesktop.platformSendWebhook(w.url,p.payload||{});}else if(p.type==='agent_plan'){state.objects.push({id:uid('obj'),type:'document',title:p.title||'Agent output',values:{body:(p.steps||[]).map((x,i)=>`${i+1}. ${x}`).join('\n')},relations:p.objectIds||[],source:'agent-plan',createdAt:now(),updatedAt:now()});}}
async function approvalDecision(id,approve){const a=state.approvals.find(x=>x.id===id);if(!a||a.status!=='pending')return;try{if(approve)await executeApprovalPayload(a.payload);a.status=approve?'approved':'rejected';a.resolvedAt=now();audit(approve?'Approval granted':'Approval rejected',a.title);await platformSave();toast(approve?'Approved and executed.':'Rejected.');render();}catch(e){toast(e.message,'error');audit('Approval execution failed',e.message);}}

function contextModal(){const options=state.objects.slice(0,120).map(o=>`<label class="v21Check"><input type="checkbox" data-v21-context-object="${o.id}"><span>${esc(objectTitle(o))} · ${esc(o.type)}</span></label>`).join('')||'<div class="empty">Create records first, or create an empty Context Space.</div>';modal('New Context Space',`<div class="v21FormGrid"><label class="v21Field span2"><span>Name</span><input id="v21ContextName" value="Project context"></label><label class="v21Field span2"><span>Web links (one per line)</span><textarea id="v21ContextLinks" rows="3"></textarea></label></div><div class="v21ContextPicker">${options}</div>`,`<div class="formActions"><button class="secondary" data-v21-close>Cancel</button><button class="primary" data-v21-context-create>Create Context Space</button></div>`);}
async function createContext(){const name=$('#v21ContextName')?.value.trim();if(!name)return;state.contexts.push({id:uid('ctx'),name,objectIds:$$('[data-v21-context-object]:checked').map(x=>x.dataset.v21ContextObject),links:($('#v21ContextLinks')?.value||'').split('\n').map(x=>x.trim()).filter(Boolean),createdAt:now(),updatedAt:now()});audit('Context Space created',name);await platformSave();closeModal();activeTab='intelligence';render();}
function openContext(id){const c=state.contexts.find(x=>x.id===id);if(!c)return;modal(c.name,`<div class="v21ContextObjects">${(c.objectIds||[]).map(id=>object(id)).filter(Boolean).map(o=>`<div><b>${esc(objectTitle(o))}</b><span>${esc(o.type)} · <code>${esc(o.id)}</code></span></div>`).join('')||'<div class="empty">No objects in this context.</div>'}</div>${(c.links||[]).length?`<div class="v21ModalSection"><b>Links</b>${c.links.map(l=>`<p>${esc(l)}</p>`).join('')}</div>`:''}`);}
function skillModal(){modal('New skill',`<div class="v21FormGrid"><label class="v21Field span2"><span>Name</span><input id="v21SkillName" value="Weekly client report"></label><label class="v21Field span2"><span>Instructions</span><textarea id="v21SkillInstructions" rows="6">Summarize progress, blockers, decisions and next actions. Cite the Qanteak objects used.</textarea></label></div>`,`<div class="formActions"><button class="secondary" data-v21-close>Cancel</button><button class="primary" data-v21-skill-create>Create skill</button></div>`);}
async function createSkill(){const name=$('#v21SkillName')?.value.trim();if(!name)return;state.skills.push({id:uid('skill'),name,instructions:$('#v21SkillInstructions')?.value.trim()||'',version:1,allowedTools:['search','read'],createdAt:now()});audit('Skill created',name);await platformSave();closeModal();render();}
function agentModal(){modal('New agent',`<div class="v21FormGrid"><label class="v21Field span2"><span>Name</span><input id="v21AgentName" value="Qanteak Project Agent"></label><label class="v21Field span2"><span>Purpose / instructions</span><textarea id="v21AgentPurpose" rows="5">Review the selected context, identify risks and prepare an actionable plan.</textarea></label><label class="v21Field"><span>Context Space</span><select id="v21AgentContext"><option value="">Workspace</option>${state.contexts.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></label><label class="v21Field"><span>Skill</span><select id="v21AgentSkill"><option value="">None</option>${state.skills.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select></label></div>`,`<div class="formActions"><button class="secondary" data-v21-close>Cancel</button><button class="primary" data-v21-agent-create>Create agent</button></div>`);}
async function createAgent(){const name=$('#v21AgentName')?.value.trim();if(!name)return;state.agents.push({id:uid('agent'),name,purpose:$('#v21AgentPurpose')?.value.trim()||'',contextId:$('#v21AgentContext')?.value||'',skillIds:[$('#v21AgentSkill')?.value].filter(Boolean),tools:['search','read','create_object'],confirmation:'workspace-policy',createdAt:now()});audit('Agent created',name);await platformSave();closeModal();render();}
function planForAgent(a){const c=state.contexts.find(x=>x.id===a.contextId),objects=(c?.objectIds||[]).map(object).filter(Boolean),skill=state.skills.find(s=>a.skillIds?.includes(s.id));const steps=[`Load ${objects.length||state.objects.length} permission-scoped workspace objects${c?` from ${c.name}`:''}.`,`Apply agent instructions: ${a.purpose||'Review current work.'}`,skill?`Apply reusable skill: ${skill.name}.`:'Use the workspace instruction policy.',`Identify risks, decisions and next actions with internal object citations.`,`Save the result as a persistent Qanteak document artifact.`];return{steps,objectIds:objects.map(o=>o.id)};}
async function runAgent(id){const a=state.agents.find(x=>x.id===id);if(!a)return;const plan=planForAgent(a);queueApproval('agent_plan',`Run agent · ${a.name}`,`${plan.steps.length} planned steps`,{type:'agent_plan',title:`${a.name} output`,steps:plan.steps,objectIds:plan.objectIds});audit('Agent plan prepared',a.name,'agent');await platformSave();activeTab='automations';render();toast('Agent plan added to the approval queue.');}

async function runResearch(contextId){const c=state.contexts.find(x=>x.id===contextId);if(!c)return;const objs=(c.objectIds||[]).map(object).filter(Boolean),lines=objs.map(o=>`- ${objectTitle(o)} [${o.type}] (${o.id})`);const report={id:uid('obj'),type:'report',title:`Research · ${c.name}`,values:{body:`Context research generated from ${objs.length} Qanteak objects.\n\n${lines.join('\n')}\n\nSynthesis:\n${summarizeObjects(objs)}`},relations:objs.map(o=>o.id),source:'qanteak-researcher',createdAt:now(),updatedAt:now()};state.objects.push(report);for(const o of objs)state.citations.push({id:uid('cite'),artifactId:report.id,objectId:o.id,label:objectTitle(o),createdAt:now()});audit('Research report created',report.title,'researcher');await platformSave();toast('Research report saved as a Qanteak artifact.');openArtifact(report.id);}
function summarizeObjects(objs){const by={};for(const o of objs)by[o.type]=(by[o.type]||0)+1;return Object.entries(by).map(([k,v])=>`${v} ${k}${v===1?'':'s'}`).join(', ')||'No scoped objects.';}
function specialistModal(kind){if(kind==='researcher'){modal('Qanteak Researcher',`<label class="v21Field"><span>Context Space</span><select id="v21SpecialContext">${state.contexts.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></label>`,`<div class="formActions"><button class="secondary" data-v21-close>Cancel</button><button class="primary" data-v21-research-run>Build cited report</button></div>`);return;}if(kind==='analyst'){modal('Qanteak Analyst',`<label class="v21Field"><span>Database</span><select id="v21AnalystSchema">${state.schemas.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select></label>`,`<div class="formActions"><button class="secondary" data-v21-close>Cancel</button><button class="primary" data-v21-analyst-run>Analyze</button></div>`);return;}if(kind==='meeting'){modal('Meeting Intelligence',`<div class="v21FormGrid"><label class="v21Field span2"><span>Meeting title</span><input id="v21MeetingTitle" value="Team meeting"></label><label class="v21Field span2"><span>Notes / transcript</span><textarea id="v21MeetingNotes" rows="12" placeholder="Decision: ...\nAction: ...\nTODO: ..."></textarea></label></div>`,`<div class="formActions"><button class="secondary" data-v21-close>Cancel</button><button class="primary" data-v21-meeting-run>Extract intelligence</button></div>`);return;}modal('People Intelligence',`<p>Qanteak will scan owners and Person properties across the universal object graph and save an ownership report.</p>`,`<div class="formActions"><button class="secondary" data-v21-close>Cancel</button><button class="primary" data-v21-people-run>Build people report</button></div>`);}
async function analystRun(){const s=schema($('#v21AnalystSchema')?.value);if(!s)return;const rows=records(s.id),nums=s.fields.filter(f=>['number','currency','percentage'].includes(f.type)),stats=nums.map(f=>{const vals=rows.map(r=>num(computedValue(r,s,f)));return`${f.label}: count ${vals.length}, sum ${vals.reduce((a,b)=>a+b,0)}, average ${vals.length?(vals.reduce((a,b)=>a+b,0)/vals.length).toFixed(2):0}, min ${vals.length?Math.min(...vals):0}, max ${vals.length?Math.max(...vals):0}`;});const report={id:uid('obj'),type:'report',title:`Analysis · ${s.name}`,values:{body:`${rows.length} records analyzed.\n\n${stats.join('\n')||'No numeric properties found.'}`},relations:rows.map(r=>r.id),source:'qanteak-analyst',createdAt:now(),updatedAt:now()};state.objects.push(report);audit('Analysis report created',report.title,'analyst');await platformSave();closeModal();openArtifact(report.id);}
async function meetingRun(){const title=$('#v21MeetingTitle')?.value.trim()||'Meeting',notes=$('#v21MeetingNotes')?.value||'',lines=notes.split(/\r?\n/).map(x=>x.trim()).filter(Boolean),decisions=lines.filter(x=>/^decision\s*:/i.test(x)),actions=lines.filter(x=>/^(action|todo)\s*:/i.test(x));const meeting={id:uid('obj'),type:'meeting',title,values:{notes,summary:`${decisions.length} decisions · ${actions.length} action items`,decisions,actions},relations:[],source:'meeting-intelligence',createdAt:now(),updatedAt:now()};state.objects.push(meeting);for(const a of actions)state.objects.push({id:uid('obj'),type:'task',title:a.replace(/^(action|todo)\s*:\s*/i,''),values:{status:'New'},relations:[meeting.id],source:'meeting-intelligence',createdAt:now(),updatedAt:now()});audit('Meeting intelligence created',`${title} · ${actions.length} tasks`,'meeting');await platformSave();closeModal();openArtifact(meeting.id);}
async function peopleRun(){const counts={};for(const o of state.objects){const names=[o.owner];const s=o.schemaId?schema(o.schemaId):null;for(const f of s?.fields||[])if(f.type==='person'){const v=computedValue(o,s,f);if(Array.isArray(v))names.push(...v);else names.push(v);}for(const n of names.filter(Boolean))counts[n]=(counts[n]||0)+1;}const body=Object.entries(counts).sort((a,b)=>b[1]-a[1]).map(([n,c])=>`${n}: ${c} owned/referenced objects`).join('\n')||'No people ownership data found.';const report={id:uid('obj'),type:'report',title:'People & ownership intelligence',values:{body},relations:[],source:'people-intelligence',createdAt:now(),updatedAt:now()};state.objects.push(report);audit('People report created',report.title,'people');await platformSave();closeModal();openArtifact(report.id);}
function openArtifact(id){const o=object(id);if(!o)return;const cites=state.citations.filter(c=>c.artifactId===id);modal(objectTitle(o),`<div class="v21Artifact"><span class="v21Kicker">${esc(o.type)}</span><pre>${esc(o.values?.body||o.values?.notes||JSON.stringify(o.values||{},null,2))}</pre>${cites.length?`<div class="v21Citations"><b>Sources</b>${cites.map(c=>`<button data-v21-artifact-open="${c.objectId}">[${esc(c.label)}]</button>`).join('')}</div>`:''}</div>`);}

function webhookModal(){modal('New webhook',`<div class="v21FormGrid"><label class="v21Field"><span>Name</span><input id="v21WebhookName" value="Qanteak webhook"></label><label class="v21Field"><span>Event</span><select id="v21WebhookEvent"><option value="object.created">object.created</option><option value="form.submitted">form.submitted</option><option value="automation.run">automation.run</option></select></label><label class="v21Field span2"><span>HTTPS endpoint</span><input id="v21WebhookUrl" type="url" placeholder="https://example.com/qanteak"></label></div>`,`<div class="formActions"><button class="secondary" data-v21-close>Cancel</button><button class="primary" data-v21-webhook-create>Create webhook</button></div>`);}
async function createWebhook(){const name=$('#v21WebhookName')?.value.trim(),url=$('#v21WebhookUrl')?.value.trim();if(!name||!/^https:\/\//i.test(url||'')){toast('Webhook requires a name and HTTPS URL.','error');return;}state.webhooks.push({id:uid('hook'),name,event:$('#v21WebhookEvent')?.value||'object.created',url,enabled:true,createdAt:now()});audit('Webhook configured',name);await platformSave();closeModal();render();}
async function toggleApi(){try{apiStatus=apiStatus.enabled?await window.qanteakDesktop.platformStopApi():await window.qanteakDesktop.platformStartApi(Number(state.platform?.port||32145));state.platform={...(state.platform||{}),apiEnabled:apiStatus.enabled,mcpEnabled:apiStatus.enabled,port:apiStatus.port};audit(apiStatus.enabled?'Local API enabled':'Local API disabled',apiStatus.enabled?apiStatus.baseUrl:'Stopped');await platformSave();render();}catch(e){toast(e.message||'Could not change API status.','error');}}
function connectorManifest(){const manifest={sdk:'qanteak-connector-v1',required:['id','name','authenticate','search','fetch'],optional:['subscribe','actions','permissions','citations'],security:{leastPrivilege:true,auditRequired:true,writeConfirmation:true},examples:CONNECTOR_CATALOG.map(([id,name,scope,gate])=>({id,name,scope,gate}))};downloadText('qanteak-connector-sdk-manifest.json',JSON.stringify(manifest,null,2),'application/json');audit('Connector SDK manifest exported','qanteak-connector-v1');}
function exportState(){downloadText(`Qanteak-${RELEASE.replace(/\s+/g,'-')}-workspace.json`,JSON.stringify(state,null,2),'application/json');audit('Workspace exported',`${state.objects.length} objects`);}
function downloadText(name,text,type='text/plain'){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function importFile(){let input=$('#v21ImportFile');if(!input){input=document.createElement('input');input.type='file';input.id='v21ImportFile';input.accept='.json,.csv,.md,.markdown,text/csv,application/json,text/markdown';input.hidden=true;document.body.append(input);input.addEventListener('change',async()=>{const file=input.files?.[0];if(!file)return;const text=await file.text();try{if(file.name.toLowerCase().endsWith('.json')){const parsed=JSON.parse(text);if(parsed.version===21&&Array.isArray(parsed.objects)){state=normalizeState(parsed);audit('Workspace imported',file.name);await platformSave();render();}else throw new Error('JSON is not a Qanteak V0.21 workspace export.');}else if(file.name.toLowerCase().endsWith('.csv'))await importCsv(file.name,text);else await importMarkdown(file.name,text);}catch(e){toast(e.message,'error');}input.value='';});}input.click();}
function parseCsv(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(q&&text[i+1]==='"'){cell+='"';i++;}else q=!q;}else if(c===','&&!q){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(x=>x!==''))rows.push(row);row=[];cell='';}else cell+=c;}row.push(cell);if(row.some(x=>x!==''))rows.push(row);return rows;}
async function importCsv(name,text){const rows=parseCsv(text);if(rows.length<1)throw new Error('CSV is empty.');const headers=rows[0].map((h,i)=>h.trim()||`Column ${i+1}`),s={id:uid('schema'),name:name.replace(/\.csv$/i,''),description:'Imported CSV',fields:headers.map((h,i)=>field('text',h,{required:i===0})),createdAt:now(),updatedAt:now()};state.schemas.push(s);for(const row of rows.slice(1)){const values={};s.fields.forEach((f,i)=>values[f.id]=row[i]??'');state.objects.push({id:uid('obj'),type:'record',schemaId:s.id,title:String(values[s.fields[0].id]||'Imported row'),values,relations:[],source:'csv-import',createdAt:now(),updatedAt:now()});}state.views.push({id:uid('view'),schemaId:s.id,name:'Table',type:'table',filters:[],sorts:[],groupBy:'',visibleFields:s.fields.map(f=>f.id),createdAt:now()});audit('CSV imported',`${name} · ${rows.length-1} records`);await platformSave();activeTab='data';render();}
async function importMarkdown(name,text){state.objects.push({id:uid('obj'),type:'document',title:name.replace(/\.(md|markdown)$/i,''),values:{body:text},relations:[],source:'markdown-import',createdAt:now(),updatedAt:now()});audit('Markdown imported',name);await platformSave();render();toast('Markdown imported as a Qanteak document object.');}

function governanceSave(){state.instructions.workspace=$('#v21WorkspaceInstructions')?.value||'';state.instructions.user=$('#v21UserInstructions')?.value||'';state.governance.requireApprovalForWrites=Boolean($('#v21RequireApproval')?.checked);state.governance.externalActionsEnabled=Boolean($('#v21ExternalActions')?.checked);state.governance.retentionDays=clamp($('#v21Retention')?.value,1,3650);state.governance.allowedTools=$$('[data-v21-tool]:checked').map(x=>x.dataset.v21Tool);state.governance.computerUseEnabled=false;audit('Governance updated',`${state.governance.allowedTools.length} allowed tools`);platformSave();toast('Governance policy saved.');render();}
function auditExport(){downloadText('Qanteak-V0.21-audit.json',JSON.stringify(state.audit,null,2),'application/json');}

function threadModal(objectId){const o=object(objectId);if(!o)return;const comments=state.comments.filter(c=>c.objectId===objectId);modal(`Thread · ${objectTitle(o)}`,`<div class="v21Thread">${comments.map(c=>`<div><b>${esc(c.author||'Local user')}</b><p>${esc(c.body)}</p><time>${esc(fmtTime(c.createdAt))}</time></div>`).join('')||'<div class="empty">No comments yet.</div>'}</div><label class="v21Field"><span>Comment / @mention</span><textarea id="v21CommentBody" rows="4"></textarea></label>`,`<div class="formActions"><button class="secondary" data-v21-close>Close</button><button class="primary" data-v21-comment-add="${objectId}">Add comment</button></div>`);}
async function addComment(objectId){const body=$('#v21CommentBody')?.value.trim();if(!body)return;state.comments.push({id:uid('comment'),objectId,body,mentions:(body.match(/@[a-zA-Z0-9._-]+/g)||[]),author:'Local user',createdAt:now()});audit('Comment added',objectTitle(object(objectId)));await platformSave();threadModal(objectId);}

function searchNow(){const q=$('#v21SearchInput')?.value.trim().toLowerCase()||'',host=$('#v21SearchResults');if(!host)return;const hits=state.objects.filter(o=>JSON.stringify(o).toLowerCase().includes(q)).slice(0,30);host.innerHTML=hits.map((o,i)=>`<button data-v21-artifact-open="${o.id}"><span><b>${esc(objectTitle(o))}</b><small>${esc(o.type)} · ${esc(o.id)}</small></span><em>[${i+1}]</em></button>`).join('')||'<div class="empty">No matching objects.</div>';}

function propertyRollupConfig(schemaId,fieldId){const s=schema(schemaId),f=s?.fields.find(x=>x.id===fieldId);if(!f||f.type!=='rollup')return;const rels=s.fields.filter(x=>x.type==='relation');modal(`Configure rollup · ${f.label}`,`<div class="v21FormGrid"><label class="v21Field"><span>Relation property</span><select id="v21RollupRelation">${rels.map(r=>`<option value="${r.id}">${esc(r.label)}</option>`).join('')}</select></label><label class="v21Field"><span>Target property</span><select id="v21RollupTarget">${state.schemas.flatMap(ts=>ts.fields.map(tf=>`<option value="${tf.id}">${esc(ts.name)} · ${esc(tf.label)}</option>`)).join('')}</select></label><label class="v21Field"><span>Operation</span><select id="v21RollupOp">${['count','sum','average','min','max','earliest','latest','percent_checked'].map(x=>`<option>${x}</option>`).join('')}</select></label></div>`,`<div class="formActions"><button class="secondary" data-v21-close>Cancel</button><button class="primary" data-v21-rollup-save="${f.id}" data-schema-id="${s.id}">Save rollup</button></div>`);}
async function saveRollup(schemaId,fieldId){const f=fieldDef(schemaId,fieldId);if(!f)return;f.relationFieldId=$('#v21RollupRelation')?.value||'';f.targetFieldId=$('#v21RollupTarget')?.value||'';f.operation=$('#v21RollupOp')?.value||'count';audit('Rollup configured',`${schema(schemaId)?.name} · ${f.label}`);await platformSave();closeModal();openSchema(schemaId);}

function scheduledTick(){const t=Date.now();for(const a of state.automations.filter(a=>a.enabled&&a.trigger?.type==='schedule')){const every=Math.max(1,Number(a.trigger.intervalMinutes||60))*60000,last=a.lastRunAt?new Date(a.lastRunAt).getTime():0;if(!last||t-last>=every)runAutomation(a.id,{source:'schedule'}).catch(e=>console.warn(e));}}
setInterval(scheduledTick,60000);

document.addEventListener('click',async e=>{
  const el=e.target.closest?.('#workspaceV021,[data-v21-tab],[data-v21-close],[data-v21-new-schema],[data-v21-schema-create],[data-v21-schema-open],[data-v21-property-new],[data-v21-property-create],[data-v21-record-new],[data-v21-record-save],[data-v21-record-edit],[data-v21-view-type],[data-v21-view-config],[data-v21-view-save],[data-v21-form-new],[data-v21-form-create],[data-v21-form-open],[data-v21-form-submit],[data-v21-new-dashboard],[data-v21-dashboard-create],[data-v21-dashboard-open],[data-v21-new-automation],[data-v21-auto-create],[data-v21-auto-run],[data-v21-auto-toggle],[data-v21-auto-delete],[data-v21-approval-approve],[data-v21-approval-reject],[data-v21-new-context],[data-v21-context-create],[data-v21-context-open],[data-v21-research-context],[data-v21-new-skill],[data-v21-skill-create],[data-v21-new-agent],[data-v21-agent-create],[data-v21-agent-run],[data-v21-agent-delete],[data-v21-specialist],[data-v21-research-run],[data-v21-analyst-run],[data-v21-meeting-run],[data-v21-people-run],[data-v21-api-toggle],[data-v21-new-webhook],[data-v21-webhook-create],[data-v21-connector-manifest],[data-v21-export],[data-v21-import],[data-v21-governance-save],[data-v21-audit-export],[data-v21-thread],[data-v21-comment-add],[data-v21-search],[data-v21-artifact-open],[data-v21-rollup-save]');
  if(!el)return;
  if(el.id==='workspaceV021'){e.preventDefault();activeTab='overview';render();return;}
  if(el.dataset.v21Tab){activeTab=el.dataset.v21Tab;render();return;}
  if(el.hasAttribute('data-v21-close')){closeModal();return;}
  if(el.hasAttribute('data-v21-new-schema')){newSchemaModal();return;}
  if(el.hasAttribute('data-v21-schema-create')){await createSchema();return;}
  if(el.dataset.v21SchemaOpen){openSchema(el.dataset.v21SchemaOpen);return;}
  if(el.dataset.v21PropertyNew){propertyModal(el.dataset.v21PropertyNew);return;}
  if(el.dataset.v21PropertyCreate){await createProperty(el.dataset.v21PropertyCreate);return;}
  if(el.dataset.v21RecordNew){recordModal(el.dataset.v21RecordNew);return;}
  if(el.dataset.v21RecordSave){await saveRecord(el.dataset.v21RecordSave,el.dataset.recordId||'');return;}
  if(el.dataset.v21RecordEdit){recordModal(el.dataset.schemaId,el.dataset.v21RecordEdit);return;}
  if(el.dataset.v21ViewType){openSchema(el.dataset.schemaId,el.dataset.v21ViewType);return;}
  if(el.dataset.v21ViewConfig){viewConfigModal(el.dataset.v21ViewConfig,el.dataset.viewType||'table');return;}
  if(el.dataset.v21ViewSave){await saveView(el.dataset.v21ViewSave,el.dataset.schemaId);return;}
  if(el.dataset.v21FormNew){formNewModal(el.dataset.v21FormNew);return;}
  if(el.dataset.v21FormCreate){await createForm(el.dataset.v21FormCreate);return;}
  if(el.dataset.v21FormOpen){openForm(el.dataset.v21FormOpen);return;}
  if(el.dataset.v21FormSubmit){await submitForm(el.dataset.v21FormSubmit);return;}
  if(el.hasAttribute('data-v21-new-dashboard')){dashboardNewModal();return;}
  if(el.hasAttribute('data-v21-dashboard-create')){await createDashboard();return;}
  if(el.dataset.v21DashboardOpen){openDashboard(el.dataset.v21DashboardOpen);return;}
  if(el.hasAttribute('data-v21-new-automation')){automationModal();return;}
  if(el.hasAttribute('data-v21-auto-create')){await createAutomation();return;}
  if(el.dataset.v21AutoRun){await runAutomation(el.dataset.v21AutoRun);return;}
  if(el.dataset.v21AutoToggle){const a=state.automations.find(x=>x.id===el.dataset.v21AutoToggle);if(a){a.enabled=!a.enabled;audit('Automation toggled',`${a.name} · ${a.enabled?'enabled':'paused'}`);await platformSave();render();}return;}
  if(el.dataset.v21AutoDelete){const a=state.automations.find(x=>x.id===el.dataset.v21AutoDelete);state.automations=state.automations.filter(x=>x.id!==el.dataset.v21AutoDelete);if(a)audit('Automation deleted',a.name);await platformSave();render();return;}
  if(el.dataset.v21ApprovalApprove){await approvalDecision(el.dataset.v21ApprovalApprove,true);return;}
  if(el.dataset.v21ApprovalReject){await approvalDecision(el.dataset.v21ApprovalReject,false);return;}
  if(el.hasAttribute('data-v21-new-context')){contextModal();return;}
  if(el.hasAttribute('data-v21-context-create')){await createContext();return;}
  if(el.dataset.v21ContextOpen){openContext(el.dataset.v21ContextOpen);return;}
  if(el.dataset.v21ResearchContext){await runResearch(el.dataset.v21ResearchContext);return;}
  if(el.hasAttribute('data-v21-new-skill')){skillModal();return;}
  if(el.hasAttribute('data-v21-skill-create')){await createSkill();return;}
  if(el.hasAttribute('data-v21-new-agent')){agentModal();return;}
  if(el.hasAttribute('data-v21-agent-create')){await createAgent();return;}
  if(el.dataset.v21AgentRun){await runAgent(el.dataset.v21AgentRun);return;}
  if(el.dataset.v21AgentDelete){const a=state.agents.find(x=>x.id===el.dataset.v21AgentDelete);state.agents=state.agents.filter(x=>x.id!==el.dataset.v21AgentDelete);if(a)audit('Agent deleted',a.name);await platformSave();render();return;}
  if(el.dataset.v21Specialist){specialistModal(el.dataset.v21Specialist);return;}
  if(el.hasAttribute('data-v21-research-run')){await runResearch($('#v21SpecialContext')?.value);return;}
  if(el.hasAttribute('data-v21-analyst-run')){await analystRun();return;}
  if(el.hasAttribute('data-v21-meeting-run')){await meetingRun();return;}
  if(el.hasAttribute('data-v21-people-run')){await peopleRun();return;}
  if(el.hasAttribute('data-v21-api-toggle')){await toggleApi();return;}
  if(el.hasAttribute('data-v21-new-webhook')){webhookModal();return;}
  if(el.hasAttribute('data-v21-webhook-create')){await createWebhook();return;}
  if(el.hasAttribute('data-v21-connector-manifest')){connectorManifest();return;}
  if(el.hasAttribute('data-v21-export')){exportState();return;}
  if(el.hasAttribute('data-v21-import')){importFile();return;}
  if(el.hasAttribute('data-v21-governance-save')){governanceSave();return;}
  if(el.hasAttribute('data-v21-audit-export')){auditExport();return;}
  if(el.dataset.v21Thread){threadModal(el.dataset.v21Thread);return;}
  if(el.dataset.v21CommentAdd){await addComment(el.dataset.v21CommentAdd);return;}
  if(el.hasAttribute('data-v21-search')){searchNow();return;}
  if(el.dataset.v21ArtifactOpen){openArtifact(el.dataset.v21ArtifactOpen);return;}
  if(el.dataset.v21RollupSave){await saveRollup(el.dataset.schemaId,el.dataset.v21RollupSave);return;}
});

document.addEventListener('dblclick',e=>{const chip=e.target.closest?.('.v21SchemaMeta span');if(!chip||!currentSchemaId)return;const text=chip.textContent||'',label=text.split(' · ')[0],s=schema(currentSchemaId),f=s?.fields.find(x=>x.label===label);if(f?.type==='rollup')propertyRollupConfig(s.id,f.id);});
document.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target?.id==='v21SearchInput')searchNow();});
document.addEventListener('click',e=>{const target=e.target.closest?.('.navItem[data-view]');if(!target)return;$('#workspaceV021')?.classList.remove('active');},true);

async function init(){
  state=normalizeState(await platformLoad());migrateV020();await platformSave();ensureNav();
  try{if(window.qanteakDesktop?.platformApiStatus)apiStatus=await window.qanteakDesktop.platformApiStatus();}catch{}
  const pill=$('#updatePill');if(pill)pill.textContent='RC9 V0.21';document.title='Qanteak OS RC9 V0.21';
  const eyebrow=$('.authEyebrow');if(eyebrow)eyebrow.textContent='Qanteak OS · RC9 V0.21';
  scheduledTick();
}
init().catch(e=>{console.error('V0.21 initialization failed',e);toast(`V0.21 initialization failed: ${e.message}`,'error');});
