const assert=require('node:assert/strict');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const {entitlementFor}=require('../electron/entitlement.cjs');
const platform=require('../electron/platform.cjs');
const now=Date.parse('2026-09-19T12:00:00Z');
assert.equal(entitlementFor(null,now).allowed,false);
assert.equal(entitlementFor({provider:'paypal',status:'active',test_mode:true},now).allowed,false);
assert.equal(entitlementFor({provider:'paypal',status:'active',current_period_end:'2026-09-18'},now).allowed,false);
assert.equal(entitlementFor({provider:'paypal',status:'trialing',trial_ends_at:'2026-09-18'},now).allowed,false);
assert.equal(entitlementFor({provider:'paypal',status:'active',ends_at:'invalid'},now).allowed,false);
assert.equal(entitlementFor({provider:'paypal',status:'cancelled',current_period_end:'2026-10-01'},now).allowed,false);
assert.equal(entitlementFor({provider:'paypal',status:'active',current_period_end:'2026-10-01'},now).allowed,true);
assert.equal(entitlementFor({provider:'internal_qa',status:'active',test_mode:true},now).allowed,true);
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'qanteak-v022-'));
const file=path.join(dir,'qanteak-v021-platform.json');
(async()=>{
 platform.configure(dir);
 const saved=platform.readState();saved.objects.push({id:'kept',title:'Preserve this work'});platform.writeState(saved);platform.writeState(saved);
 fs.writeFileSync(file,'broken{');assert.equal(platform.readState().objects[0].id,'kept');
 assert.ok(fs.readdirSync(dir).some(name=>name.includes('.damaged-')));
 fs.rmSync(file+'.bak');fs.writeFileSync(file,'unrecoverable{');
 assert.throws(()=>platform.readState(),/preserved/);assert.equal(fs.readFileSync(file,'utf8'),'unrecoverable{');
 assert.throws(()=>platform.writeState({objects:[]}),/JSON|Unexpected/);assert.equal(fs.readFileSync(file,'utf8'),'unrecoverable{');
 fs.writeFileSync(file,JSON.stringify(saved));
 const port=35000+Math.floor(Math.random()*15000);const api=await platform.startApi(port);
 const call=()=>fetch(api.baseUrl+'/mcp',{method:'POST',headers:{Authorization:'Bearer '+api.token,'Content-Type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/call',params:{name:'qanteak_create_object',arguments:{type:'note',title:'API test'}}})}).then(r=>r.json());
 assert.equal((await fetch(api.baseUrl+'/v1/objects')).status,401);
 assert.equal((await call()).error.code,-32003);assert.equal(platform.readState().objects.length,1);
 let state=platform.readState();state.governance.requireApprovalForWrites=false;state.governance.allowedTools=[];platform.writeState(state);
 assert.equal((await call()).error.code,-32003);
 state=platform.readState();state.governance.allowedTools=['create_object'];platform.writeState(state);
 assert.ok((await call()).result);assert.equal(platform.readState().objects.length,2);
 await platform.stopApi();console.log('Reliability tests OK: entitlement expiry/test isolation, non-destructive corruption recovery, API authentication and MCP write policy.');
})().catch(error=>{console.error(error);process.exitCode=1}).finally(async()=>{try{await platform.stopApi()}catch{}fs.rmSync(dir,{recursive:true,force:true})});
